extension CompoundCatalog {
    static let organic: [KnownCompound] = [
        KnownCompound("CH3OH", "Methanol", systematic: "methanol", aliases: ["Wood alcohol"],
            hazards: [HazardNote(.toxic, "Poisonous; can cause blindness or death if swallowed."),
                      HazardNote(.flammable, "Burns with a nearly invisible flame.")]),
        KnownCompound("C2H6O", "Ethanol", systematic: "ethanol", aliases: ["Ethyl alcohol", "Drinking alcohol"],
            hazards: [HazardNote(.flammable, "Vapor ignites easily.")],
            isomers: "Dimethyl ether has the same formula (C₂H₆O) but a different structure."),
        KnownCompound("C3H8", "Propane", systematic: "propane",
            hazards: [HazardNote(.flammable, "Ignites easily."),
                      HazardNote(.explosive, "Gas accumulates and explodes with air.")]),
        KnownCompound("C4H10", "Butane", systematic: "butane",
            hazards: [HazardNote(.flammable, "Ignites easily."),
                      HazardNote(.explosive, "Gas accumulates and explodes with air.")],
            isomers: "Isobutane (2-methylpropane) has the same formula."),
        KnownCompound("C2H4", "Ethylene", systematic: "ethene",
            hazards: [HazardNote(.flammable, "Ignites easily.")]),
        KnownCompound("C2H2", "Acetylene", systematic: "ethyne",
            hazards: [HazardNote(.flammable, "Burns extremely hot."),
                      HazardNote(.explosive, "Can decompose explosively under pressure.")]),
        KnownCompound("C6H6", "Benzene", systematic: "benzene",
            hazards: [HazardNote(.flammable, "Vapor ignites easily."),
                      HazardNote(.healthHazard, "Causes cancer with repeated exposure."),
                      HazardNote(.toxic, "Harmful if inhaled or swallowed.")]),
        KnownCompound("C2H4O2", "Acetic acid", systematic: "ethanoic acid", aliases: ["Vinegar (dilute)"],
            hazards: [HazardNote(.corrosive, "Concentrated acid burns skin and eyes."),
                      HazardNote(.flammable, "Vapor ignites when warm.")],
            isomers: "Methyl formate has the same formula."),
        KnownCompound("C6H12O6", "Glucose", systematic: "glucose", aliases: ["Blood sugar", "Dextrose"],
            isomers: "Fructose and galactose also have the formula C₆H₁₂O₆."),
        KnownCompound("C12H22O11", "Sucrose", systematic: "sucrose", aliases: ["Table sugar"],
            isomers: "Lactose and maltose also have the formula C₁₂H₂₂O₁₁."),
        KnownCompound("CH2O", "Formaldehyde", systematic: "methanal",
            hazards: [HazardNote(.toxic, "Toxic gas that irritates airways and eyes."),
                      HazardNote(.healthHazard, "Causes cancer.")]),
        KnownCompound("CH3Cl", "Chloromethane", systematic: "chloromethane",
            hazards: [HazardNote(.flammable, "Flammable gas."),
                      HazardNote(.healthHazard, "Harms the nervous system.")]),
        KnownCompound("CHCl3", "Chloroform", systematic: "trichloromethane",
            hazards: [HazardNote(.toxic, "Harmful to breathe or swallow."),
                      HazardNote(.healthHazard, "Suspected carcinogen; harms the liver and kidneys.")]),
        KnownCompound("CCl4", "Carbon tetrachloride", systematic: "tetrachloromethane",
            hazards: [HazardNote(.toxic, "Toxic to the liver and kidneys."),
                      HazardNote(.environmental, "Damages the ozone layer.")]),
    ]
}
